# Generated by Django 6.0 on 2025-12-31 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('codename', models.CharField(max_length=64, unique=True)),
                ('faction', models.CharField(max_length=64)),
                ('morph', models.CharField(blank=True, max_length=255)),
                ('hat', models.CharField(blank=True, max_length=255)),
                ('nvg_color', models.CharField(blank=True, max_length=32)),
                ('shirt', models.CharField(blank=True, max_length=64)),
                ('pants', models.CharField(blank=True, max_length=64)),
                ('skin_r', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skin_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skin_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ntag', models.CharField(blank=True, max_length=128)),
                ('cntag_r', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cntag_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cntag_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rtag', models.TextField(blank=True)),
                ('crtag_r', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crtag_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('crtag_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rhat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
