# Generated by Django 6.0 on 2025-12-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lore',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
