# Generated by Django 6.0 on 2026-01-01 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_lore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-created_at'], 'verbose_name': 'Personaje', 'verbose_name_plural': 'Personajes'},
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['codename'], name='characters__codenam_3bb7ae_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['owner', 'created_at'], name='characters__owner_i_8ed87b_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['faction'], name='characters__faction_677fac_idx'),
        ),
    ]
