# Generated by Django 6.0 on 2026-01-01 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='codename',
            field=models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='country',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hat',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='lore',
            field=models.CharField(blank=True, max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='morph',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='ntag',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='nvg_color',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='pants',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='rtag',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='shirt',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
    ]
