# Generated by Django 6.0 on 2026-01-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_codename_alter_character_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='cntag_b',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cntag_g',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='cntag_r',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='crtag_b',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='crtag_g',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='crtag_r',
            field=models.PositiveSmallIntegerField(blank=True, default=255, null=True),
        ),
    ]
