# Generated by Django 6.0 on 2026-01-02 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_alter_character_cntag_b_alter_character_cntag_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(max_length=32, validators=[django.core.validators.MaxLengthValidator(64)]),
        ),
    ]
