# Generated by Django 6.0 on 2026-01-02 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True, help_text='Enlaces a evidencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ban_type', models.CharField(choices=[('temporary', 'Temporal'), ('permanent', 'Permanente')], default='temporary', max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duración en días (solo para bans temporales)', null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('can_appeal', models.BooleanField(default=True)),
                ('appealed', models.BooleanField(default=False)),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_response', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='warn',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warn',
            name='appeal_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warn',
            name='appeal_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_appeals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warn',
            name='appeal_response',
            field=models.TextField(blank=True, help_text='Respuesta del moderador a la apelación'),
        ),
        migrations.AddField(
            model_name='warn',
            name='appealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warn',
            name='appealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warn',
            name='appealed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appealed_warns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warn',
            name='evidence',
            field=models.TextField(blank=True, help_text='Enlaces a evidencia (Discord, videos, etc.)'),
        ),
        migrations.AddField(
            model_name='warn',
            name='expires_after_days',
            field=models.PositiveIntegerField(default=30, help_text='Días hasta que expire el warn'),
        ),
        migrations.AddField(
            model_name='warn',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], default=1, help_text='Severidad del warn'),
        ),
        migrations.AddField(
            model_name='warn',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('appealed', 'Apelado'), ('removed', 'Removido')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='scope',
            field=models.CharField(choices=[('global', 'Moderation Lead'), ('moderation', 'Moderación General'), ('ingame', 'In-Game Moderation'), ('discord', 'Discord Moderation'), ('roleplay', 'Roleplay Moderation')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='warn',
            index=models.Index(fields=['target', 'status'], name='users_warn_target__b81c43_idx'),
        ),
        migrations.AddIndex(
            model_name='warn',
            index=models.Index(fields=['expires_at'], name='users_warn_expires_95f10b_idx'),
        ),
        migrations.AddField(
            model_name='ban',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ban',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_bans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ban',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['target', 'is_active'], name='users_ban_target__d21c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='ban',
            index=models.Index(fields=['ends_at'], name='users_ban_ends_at_f78a53_idx'),
        ),
    ]
