# Generated by Django 6.0 on 2026-01-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ban_alter_warn_options_user_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='appeal_message',
            field=models.TextField(blank=True, help_text='Mensaje de apelación del usuario'),
        ),
        migrations.AddField(
            model_name='warn',
            name='appeal_message',
            field=models.TextField(blank=True, help_text='Mensaje de apelación del usuario'),
        ),
        migrations.AddField(
            model_name='warn',
            name='last_appealed',
            field=models.DateTimeField(blank=True, help_text='Última vez que se apeló', null=True),
        ),
    ]
