# Generated by Django 6.0 on 2026-01-02 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ban_appeal_message_warn_appeal_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='appeal_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ban',
            name='appeal_responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_ban_appeals', to=settings.AUTH_USER_MODEL),
        ),
    ]
