# Generated by Django 6.0 on 2026-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ban_appeal_responded_at_ban_appeal_responded_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'verbose_name': 'Staff Role', 'verbose_name_plural': 'Staff Roles'},
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Higher level = more permissions'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='scope',
            field=models.CharField(choices=[('global', 'Global (Admin)'), ('moderation', 'Moderation'), ('ingame', 'In-Game'), ('discord', 'Discord'), ('rp_roleplay', 'Roleplay Team'), ('rp_faction', 'Faction Moderation'), ('rp_actors', 'Actors Supervision')], max_length=20),
        ),
    ]
