# Generated by Django 6.0 on 2026-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_staffrole_options_alter_staffrole_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'verbose_name': 'Rol de Staff', 'verbose_name_plural': 'Roles de Staff'},
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nivel más alto = más permisos'),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='scope',
            field=models.CharField(choices=[('global', 'Administración Global'), ('moderation', 'Moderación General'), ('ingame', 'Moderación In-Game'), ('discord', 'Moderación Discord'), ('rp_roleplay', 'Equipo Roleplay'), ('rp_faction', 'Moderación Facciones'), ('rp_actors', 'Supervisión Actores')], max_length=20),
        ),
    ]
