# Generated by Django 6.0 on 2026-01-05 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_alter_character_faction'),
        ('users', '0007_alter_staffrole_options_alter_staffrole_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_login', 'Inicio de sesión'), ('user_logout', 'Cierre de sesión'), ('permissions_update', 'Actualización de permisos'), ('role_assigned', 'Rol asignado'), ('role_removed', 'Rol removido'), ('warn_created', 'Advertencia creada'), ('warn_updated', 'Advertencia actualizada'), ('warn_removed', 'Advertencia eliminada'), ('warn_appealed', 'Advertencia apelada'), ('warn_appeal_responded', 'Respuesta a apelación'), ('ban_created', 'Baneo creado'), ('ban_revoked', 'Baneo revocado'), ('ban_appealed', 'Baneo apelado'), ('ban_appeal_responded', 'Respuesta a apelación de baneo'), ('character_created', 'Personaje creado'), ('character_updated', 'Personaje actualizado'), ('character_deleted', 'Personaje eliminado'), ('ssu_status_changed', 'Estado SSU cambiado'), ('rp_file_edited', 'Archivo RP editado'), ('faction_moderated', 'Facción moderada'), ('actor_supervised', 'Actor supervisado')], max_length=50)),
                ('details', models.JSONField(default=dict, help_text='Detalles adicionales en formato JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ban')),
                ('target_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
                ('target_user', models.ForeignKey(blank=True, help_text='Usuario afectado por la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_warn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.warn')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='users_audit_action__9f1ecf_idx'), models.Index(fields=['action_user', 'created_at'], name='users_audit_action__9bff43_idx'), models.Index(fields=['target_user', 'created_at'], name='users_audit_target__c5e8f8_idx')],
            },
        ),
    ]
