# Generated by Django 6.0 on 2025-12-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_twilight', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteState',
        ),
    ]
